#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "bytes.usc.edu";
$SERVER_PORT = 3001;
$COURSE_NAME = "CS356";
$AUTOGRADE_TIMEOUT = 0;
1;
